### ISSUE TITLE
Доработка процедуры импорта объектов в приложение.

### ISSUE THREAD

**Issue by IvahnoSV** [Parusnik/parus-electronic-inventory-oracle#1]
Необходимо доработать процедуру импорта инвентарных объектов в приложение Parus Smart Inventory:
При загрузке исключить уникальность по наименованию объекта- поле ItemName.

**Comment by alexbocharov** [comment]
> Необходимо доработать процедуру импорта инвентарных объектов в приложение Parus Smart Inventory:
> При загрузке исключить уникальность по наименованию объекта- поле ItemName.

Ошибка не в процедурах, а в структуре данных самого мобильного приложения.

Для решения данной проблемы прийдется вернуться к совместному импорту объектов и штрих-кодов, что позволит проверять комбинацию `ItemName` и `ItemSku`.

**Comment by IvahnoSV** [comment]
> Ошибка не в процедурах, а в структуре данных самого мобильного приложения.
> 
> Для решения данной проблемы прийдется вернуться к совместному импорту объектов и штрих-кодов, что позволит проверять комбинацию `ItemName` и `ItemSku`.

Хорошо, можно вернуться к совместному импорту объектов и штрих-кодов. Что изменится в этом случае для пользователя?

**Comment by alexbocharov** [comment]
Упадет скорость импорта объектов, что скажется на импорте больших файлов Objects.csv

**Comment by alexbocharov** [comment]
В любом случае альтернативы этому нет

**Comment by alexbocharov** [comment]
В ближайшее время будет выпущено обновление

**Comment by IvahnoSV** [comment]
Возможно ли при загрузке файлов на экране отображать значок, символизирующий загрузку, до тех пор, пока загрузка не дойдёт до конца? Да, на данный момент немного изменяется цвет кнопки импорт, но это недостаточно наглядно.

**Comment by alexbocharov** [comment]
Это подтвержденный баг, т.к. индикатор выполнения выводится и пропадает непосредственно перед завершением импорта

**Comment by alexbocharov** [comment]
https://github.com/Parusnik/parus-electronic-inventory-oracle/commit/a0d1113f40a96c680be1f90499cc160292465dab Исправлена ошибка с выгрузкой мнемокода местоположения в объектах (должно быть наименование)

**Comment by alexbocharov** [comment]
**Version 1.4.1.20603 (204) Dec 03, 2020 at 14:35**

Changes
* Fixed bug with data import
* Fixed activity indicator when importing/exporting data

**Comment by alexbocharov** [comment]
Для корректной работы данные по объектам должны быть заново выгружены в csv.
